// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bymtrouruelilzgyjwph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5bXRyb3VydWVsaWx6Z3lqd3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3OTg4MjcsImV4cCI6MjA1NTM3NDgyN30.vSTSNxStlYFHP4o4U30cxk4-vMG_wTOeI6ZG2xtSy2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);